export const ADD_FOLDER = 'ADD_FOLDER'
export const DELETE_FOLDER = 'DELETE_FOLDER'
export const EDIT_FOLDER = 'EDIT_FOLDER'

export const SET_INPUT_FOLDER_TITLE = 'SET_INPUT_FOLDER_TITLE'
export const SET_ACTIVE_FOLDER_ID = 'SET_ACTIVE_FOLDER_ID'
export const RESET_FOLDER_INPUT = 'RESET_FOLDER_INPUT'
export const SELECTED_FOLDER_TITLE = 'SELECTED_FOLDER_TITLE'

// открытие и закрытие диалогового окна для создания названия папки
export const OPEN_FOLDER_TITLE_DIALOG = 'OPEN_FOLDER_TITLE_DIALOG'
export const CLOSE_FOLDER_TITLE_DIALOG = 'CLOSE_FOLDER_TITLE_DIALOG'
// открытие и закрытие диологового окна для редактирования названия папки
export const OPEN_EDIT_FOLDER_TITLE_DIALOG = 'OPEN_EDIT_FOLDER_TITLE_DIALOG'
export const CLOSE_EDIT_FOLDER_TITLE_DIALOG = 'CLOSE_EDIT_FOLDER_TITLE_DIALOG'
// открытие и закрытие контекстного меню при нажатии ПКМ
export const OPEN_FOLDER_CONTEXT_MENU = 'OPEN_FOLDER_CONTEXT_MENU'
export const CLOSE_FOLDER_CONTEXT_MENU = 'CLOSE_FOLDER_CONTEXT_MENU'

export const ADD_NOTE = 'ADD_NOTE'
export const DELETE_NOTE = 'DELETE_NOTE'
export const EDIT_NOTE = 'EDIT_NOTE'

export const SET_INPUT_NOTE_TITLE = 'SET_INPUT_NOTE_TITLE'
export const SET_ACTIVE_NOTE_ID = 'SET_ACTIVE_NOTE_ID'
export const RESET_ACTIVE_NOTE_ID = 'RESET_ACTIVE_NOTE_ID'
export const RESET_NOTE_INPUT = 'RESET_NOTE_INPUT'
export const SELECTED_NOTE_TITLE_AND_DATE = 'SELECTED_NOTE_TITLE_AND_DATE'
export const SET_INPUT_NOTE_CONTENT = 'SET_INPUT_NOTE_CONTENT'
export const SELECTED_NOTE_CONTENT = 'SELECTED_NOTE_CONTENT'

export const ENABLE_EDIT_CONTENT_MODE = 'ENABLE_EDIT_CONTENT_MODE'
export const DISABLE_EDIT_CONTENT_MODE = 'DISABLE_EDIT_CONTENT_MODE'

export const OPEN_NOTES_TITLE_DIALOG = 'OPEN_NOTES_TITLE_DIALOG'
export const CLOSE_NOTES_TITLE_DIALOG = 'CLOSE_NOTES_TITLE_DIALOG'

export const OPEN_EDIT_NOTE_TITLE_DIALOG = 'OPEN_EDIT_NOTE_TITLE_DIALOG'
export const CLOSE_EDIT_NOTE_TITLE_DIALOG = 'CLOSE_EDIT_NOTE_TITLE_DIALOG'
