export default {
    ADD_FOLDER: 'ADD_FOLDER',
    DELETE_FOLDER: 'DELETE_FOLDER',
    EDIT_FOLDER: 'EDIT_FOLDER',

    SET_INPUT_TITLE: 'SET_INPUT_TITLE',
    SET_INPUT_ID: 'SET_INPUT_ID',
    RESET_INPUT: 'RESET_INPUT',

    OPEN_FOLDER_TITLE_DIALOG: 'OPEN_FOLDER_TITLE_DIALOG',
    CLOSE_FOLDER_TITLE_DIALOG: 'CLOSE_FOLDER_TITLE_DIALOG',

    SELECT_FOLDER:'SELECT_FOLDER',
}