export const ADD_FOLDER = 'ADD_FOLDER'
export const DELETE_FOLDER = 'DELETE_FOLDER'
export const EDIT_FOLDER = 'EDIT_FOLDER'

export const SET_INPUT_TITLE = 'SET_INPUT_TITLE'
export const SET_INPUT_ID = 'SET_INPUT_ID'
export const RESET_INPUT = 'RESET_INPUT'

export const OPEN_FOLDER_TITLE_DIALOG = 'OPEN_FOLDER_TITLE_DIALOG'
export const CLOSE_FOLDER_TITLE_DIALOG = 'CLOSE_FOLDER_TITLE_DIALOG'
